### ISSUE TITLE
Could We consider using `eslint-plugin-jsx-a11y`?

### ISSUE THREAD

**Issue by diegonvs** [liferay/eslint-config-liferay#190]
It can be very helpful for enforcing people for writing accessible markup. 

From README file:

_Ryan Florence built out this awesome runtime-analysis tool called react-a11y. It is super useful. However, since you're probably already using linting in your project, this plugin comes for free and closer to the actual development process. Pairing this plugin with an editor lint plugin, you can bake accessibility standards into your application in real-time._

Since[ `react-a11y` it's deprecated in favor of `react-axe`](https://github.com/reactjs/react-a11y#%EF%B8%8Fdeprecation-notice-%EF%B8%8F), could we consider also, using `react-axe`?

Is there a preliminar discussion about it?

-----

More from a11y topic, this week I ran a `git grep aria-label` just to see wrong usages and I created this gist: https://gist.github.com/diegonvs/9fb0a1deef30cfacb0583817f24a048b#file-just-aria-label-txt-L22

Is there a way to enforce devs for avoid using hard coded strings on aria-* attrs?

**Comment by wincent** [comment]
> Could We consider using `eslint-plugin-jsx-a11y`?

I think you already answered your own question on that front:

> [`react-a11y` it's deprecated in favor of `react-axe`](https://github.com/reactjs/react-a11y#%EF%B8%8Fdeprecation-notice-%EF%B8%8F)

So, yeah, we'd need to find an alternative. I am not aware of any existing integration of react-axe via eslint, but all I did was search for "eslint" in their repo and found nothing beyond a few internal usages.

> Is there a preliminar discussion about it?

Couldn't find anything in the liferay-frontend-guidelines or liferay-npm-tools repo, or in this one.

It might be appropriate to create a ticket in the guidelines repo and discuss it there because the solution may or may not end up involving ESLint. Up to you though; the main thing is starting the conversation and you've already done that.

**Comment by diegonvs** [comment]
Closing in favor of liferay/liferay-frontend-guidelines#174
